// Design Principles & Patterns — interactive map data (single source of truth).
// Consumed by dpmap_build.js to emit the standalone HTML prototypes
// (dpmap_hybrid.html + dpmap_tree.html). Style-agnostic content.
//
// Node shape:
//   id, fam, name, tag, intent,
//   structure: [[role, desc], ...],
//   use: [..], avoid: [..], pros: [..], cons: [..],
//   code: string (\n separated), q, a (one interview Q + answer),
//   rel: [nodeId, ...]  (related concepts),
//   pdf: relative path to existing deep-dive | null

const GOF = '../2026-06-14 Design Patterns/';
const SOLID = '../2026-06-12 patterns DDD, event-driven, SOLID, CQRS/SOLID/patterns_04_solid_en.png';
const DDD_TAC = '../2026-06-12 patterns DDD, event-driven, SOLID, CQRS/DDD/patterns_02_ddd_tactical_en.png';

// Three top-level groups; each has ordered sub-groups; each node belongs to a sub-group.
const GROUPS = [
  { id:'principle',     name:'Principles',          accent:'#FB923C', blurb:`Writing code that survives change — SOLID plus core heuristics.` },
  { id:'gof',           name:'GoF Design Patterns',  accent:'#CBD5E1', blurb:`The 23 Gang-of-Four patterns — creational, structural, behavioral.` },
  { id:'architectural', name:'Architectural',        accent:'#2DD4BF', blurb:`How the app is layered — presentation, domain, data.` },
];
const SUBS = [
  { id:'solid',        group:'principle',     name:'SOLID',                accent:'#FB923C', blurb:`Five class-level principles.` },
  { id:'simplicity',   group:'principle',     name:'Simplicity & clarity', accent:'#FBBF24', blurb:`Keep it lean and obvious.` },
  { id:'coupling',     group:'principle',     name:'Coupling & OO design',  accent:'#F97316', blurb:`Low coupling, sane object graphs.` },
  { id:'grasp',        group:'principle',     name:'GRASP',                 accent:'#FDBA74', blurb:`Assigning responsibilities (Larman).` },
  { id:'creational',   group:'gof',           name:'Creational',            accent:'#4ADE80', blurb:`How objects get made.` },
  { id:'structural',   group:'gof',           name:'Structural',            accent:'#38BDF8', blurb:`How objects compose.` },
  { id:'behavioral',   group:'gof',           name:'Behavioral',            accent:'#A78BFA', blurb:`How objects collaborate.` },
  { id:'presentation', group:'architectural', name:'Presentation',          accent:'#2DD4BF', blurb:`UI / view layering.` },
  { id:'data',         group:'architectural', name:'Data & persistence',    accent:'#22D3EE', blurb:`Domain ↔ database.` },
  { id:'composition',  group:'architectural', name:'Composition',           accent:'#5EEAD4', blurb:`Wiring dependencies.` },
];

const NODES = [
  // ---------- PRINCIPLES ----------
  { id:'srp', fam:'principle', name:'SRP', full:`Single Responsibility`, tag:`One class, one reason to change`,
    intent:`A module should have one reason to change — it answers to a single actor or stakeholder.`,
    structure:[[`Actor`,`the stakeholder a module serves`],[`Responsibility`,`one axis of change`],[`Boundary`,`split when two actors collide`]],
    use:[`Policy, persistence and formatting are tangled in one class`,`Two teams edit the same file for different reasons`],
    avoid:[`Splitting into anemic one-method classes with no cohesion`],
    pros:[`Localized, low-risk change`,`Smaller, focused tests`], cons:[`Over-splitting scatters related logic`,`More files to navigate`],
    code:`// one class, three actors -> split by reason to change\nclass Payroll {}        // finance\nclass EmployeeRepo {}   // DBA\nclass HoursReport {}    // ops`,
    q:`Does SRP mean one method per class?`, a:`No — one reason to change. A class can have many methods if they all serve the same actor.`,
    rel:['ocp','soc','isp','high-cohesion'], pdf:SOLID },

  { id:'ocp', fam:'principle', name:'OCP', full:`Open / Closed`, tag:`Open to extend, closed to modify`,
    intent:`Open for extension, closed for modification — add new behavior by adding code, not editing what already works.`,
    structure:[[`Abstraction`,`stable contract clients depend on`],[`Extension`,`new implementation added, not edited`]],
    use:[`A switch grows a new branch every feature`,`Plugin / variation points`],
    avoid:[`Speculative abstraction before a second variant exists (YAGNI)`],
    pros:[`New cases can't break old ones`,`Cleaner diffs and reviews`], cons:[`Indirection`,`Costly if the abstraction is guessed wrong`],
    code:`interface Shape { area(): number }\nclass Circle implements Shape { area(){ /* ... */ } }\n// add Square as a new class — Calculator stays untouched`,
    q:`How do you actually enforce OCP?`, a:`Find the axis of change, hide it behind a polymorphic seam (interface/strategy), and depend on the abstraction.`,
    rel:['strategy','dip','lsp','protected-variations'], pdf:SOLID },

  { id:'lsp', fam:'principle', name:'LSP', full:`Liskov Substitution`, tag:`Subtypes must be substitutable`,
    intent:`A subtype must be usable anywhere its base type is expected, without breaking behavior.`,
    structure:[[`Base contract`,`preconditions, postconditions, invariants`],[`Subtype`,`may not strengthen pre- or weaken post-conditions`]],
    use:[`Designing inheritance hierarchies`,`Validating an "is-a" claim before subclassing`],
    avoid:[`Forcing inheritance where behavior really differs — compose instead`],
    pros:[`Polymorphism stays safe`,`Fewer instanceof checks`], cons:[`Hard to verify`,`Violations are subtle (Square/Rectangle)`],
    code:`// violation: Square breaks Rectangle's contract\nclass Rectangle { setW(w){} setH(h){} }\nclass Square extends Rectangle {} // setW also changes H -> surprises callers`,
    q:`Give a classic LSP violation.`, a:`Square extends Rectangle: setting width independently of height breaks code that assumes Rectangle semantics.`,
    rel:['ocp','isp','coi'], pdf:SOLID },

  { id:'isp', fam:'principle', name:'ISP', full:`Interface Segregation`, tag:`Many small interfaces beat one fat one`,
    intent:`Clients should not be forced to depend on methods they don't use.`,
    structure:[[`Role interface`,`narrow, client-specific`],[`Implementer`,`composes several role interfaces`]],
    use:[`A "god" interface forces empty or throwing methods`,`Different clients need different slices`],
    avoid:[`Shattering into so many interfaces that cohesion is lost`],
    pros:[`Lower coupling`,`Implementations stay honest`], cons:[`More types`,`Risk of over-segmentation`],
    code:`// instead of Machine { print; scan; fax }\ninterface Printer { print() }\ninterface Scanner { scan() }\nclass SimplePrinter implements Printer {}`,
    q:`How does ISP relate to SRP?`, a:`SRP is about a class's reason to change; ISP applies the same cohesion idea to interfaces, from the client's point of view.`,
    rel:['srp','dip','lsp'], pdf:SOLID },

  { id:'dip', fam:'principle', name:'DIP', full:`Dependency Inversion`, tag:`Depend on abstractions, not concretions`,
    intent:`High-level and low-level modules both depend on abstractions, not on each other; the abstraction doesn't depend on details — details implement it.`,
    structure:[[`Port`,`abstraction owned by the domain layer`],[`Adapter`,`low-level detail implements the port`]],
    use:[`Keep the domain free of DB/framework imports`,`Swap implementations, test in isolation`],
    avoid:[`Trivial code with a single, stable implementation`],
    pros:[`Testable, swappable`,`Clean domain core`], cons:[`More wiring`,`Needs a DI mechanism/container`],
    code:`interface OrderRepo { save(o: Order): Promise<void> }\nclass OrderService { constructor(private repo: OrderRepo) {} }\n// infra: class SqlOrderRepo implements OrderRepo {}`,
    q:`DIP vs DI?`, a:`DIP is the principle (depend on abstractions). DI — constructor injection, containers — is one mechanism that realizes it.`,
    rel:['dependency-injection','repository','ocp'], pdf:SOLID },

  { id:'dry', fam:'principle', name:'DRY', full:`Don't Repeat Yourself`, tag:`One authoritative source of knowledge`,
    intent:`Every piece of knowledge should have a single, unambiguous representation in the system.`,
    structure:[[`Knowledge`,`a rule, decision or fact`],[`Single source`,`one place that owns it`]],
    use:[`The same business rule is copy-pasted in three places`,`Magic numbers duplicated everywhere`],
    avoid:[`Coupling unrelated code that merely looks similar (false DRY)`],
    pros:[`One place to change`,`Fewer divergence bugs`], cons:[`The wrong abstraction is worse than duplication`,`Premature DRY couples`],
    code:`if (user.age >= 18) ...   // here\nif (u.age >= 18) ...      // and here\nconst isAdult = u => u.age >= 18   // single source`,
    q:`When is duplication better than DRY?`, a:`When the similarity is coincidental. Don't couple two things just because they look alike — prefer duplication over the wrong abstraction.`,
    rel:['soc','kiss','srp'], pdf:null },

  { id:'kiss', fam:'principle', name:'KISS', full:`Keep It Simple`, tag:`Prefer the simplest thing that works`,
    intent:`Favor simple, obvious solutions; complexity must earn its place.`,
    structure:[[`Simplicity`,`the fewest moving parts`],[`Justification`,`add complexity only when measured`]],
    use:[`Choosing between a clever and an obvious solution`,`Reviewing over-engineered code`],
    avoid:[`Over-simplifying past real requirements`],
    pros:[`Readable, maintainable`,`Faster onboarding`], cons:[`"Simple" is subjective`,`Can hide flexibility you'll need`],
    code:`// clever:\nconst isEven = n => !(n & 1)\n// kiss:\nconst isEven = n => n % 2 === 0`,
    q:`Is KISS in tension with design patterns?`, a:`Yes — patterns add structure. Apply them when complexity is real, not preemptively; otherwise KISS and YAGNI win.`,
    rel:['yagni','dry','soc'], pdf:null },

  { id:'yagni', fam:'principle', name:'YAGNI', full:`You Aren't Gonna Need It`, tag:`Build it when you actually need it`,
    intent:`Don't add functionality until it is genuinely required.`,
    structure:[[`Now`,`the requirement in front of you`],[`Later`,`speculative needs you defer`]],
    use:[`Tempted to add "future-proof" config or flags`,`Premature generalization`],
    avoid:[`Skipping genuinely-known near-term needs or basic extensibility`],
    pros:[`Less code and maintenance`,`Faster delivery`], cons:[`Some change is costly to retrofit`,`Needs judgment`],
    code:`// YAGNI: don't build a plugin system for one impl\nclass Notifier { send(msg){ email(msg) } }\n// add the abstraction when the 2nd channel actually arrives`,
    q:`YAGNI vs OCP — don't they conflict?`, a:`They balance. Don't pre-abstract (YAGNI); when the second variant appears, refactor toward OCP. The rule of three.`,
    rel:['kiss','ocp','dry'], pdf:null },

  { id:'lod', fam:'principle', name:'LoD', full:`Law of Demeter`, tag:`Only talk to your immediate friends`,
    intent:`An object should only call methods on itself, its fields, its parameters, and objects it creates — not reach through chains.`,
    structure:[[`Direct collaborator`,`one hop is allowed`],[`Train wreck`,`a.b().c().d() couples you to internals`]],
    use:[`Reducing coupling to a deep object graph`,`Encapsulating navigation behind intent`],
    avoid:[`Adding endless delegate methods that bloat the API`],
    pros:[`Lower coupling`,`Refactor-friendly`], cons:[`Delegation boilerplate`,`Fluent APIs legitimately chain`],
    code:`// violates LoD:\norder.getCustomer().getAddress().getCity()\n// tell, don't ask:\norder.shipToCity()`,
    q:`Does LoD ban all method chaining?`, a:`No. Fluent/builder chains return the same object or type. LoD targets reaching through foreign object graphs.`,
    rel:['coi','soc','srp'], pdf:null },

  { id:'coi', fam:'principle', name:'CoI', full:`Composition over Inheritance`, tag:`Has-a is more flexible than is-a`,
    intent:`Reuse behavior by composing small objects rather than inheriting from base classes.`,
    structure:[[`Component`,`small, focused collaborator`],[`Host`,`delegates to components at runtime`]],
    use:[`Behavior varies along multiple axes`,`Avoiding deep, fragile hierarchies`],
    avoid:[`A genuine, stable is-a relationship with a shared contract`],
    pros:[`Runtime flexibility`,`Avoids the fragile base class`], cons:[`More objects and wiring`,`Indirection`],
    code:`// inheritance explosion -> compose instead\nclass Player { constructor(private move: MoveStrategy) {} }\nnew Player(new FlyMove())`,
    q:`Why "favor" composition rather than always use it?`, a:`Inheritance still fits a true is-a with a shared contract; composition wins when behavior varies or you'd subclass purely for reuse.`,
    rel:['strategy','decorator','lsp'], pdf:null },

  { id:'soc', fam:'principle', name:'SoC', full:`Separation of Concerns`, tag:`Different concerns, different modules`,
    intent:`Split a system so each part addresses a distinct concern — UI, domain, persistence.`,
    structure:[[`Concern`,`one dimension of the problem`],[`Layer / module`,`owns exactly that concern`]],
    use:[`Layered or hexagonal architecture`,`UI logic leaking into the domain`],
    avoid:[`Over-layering tiny apps — ceremony without benefit`],
    pros:[`Independent change and testing`,`Clear ownership`], cons:[`More indirection`,`Cross-cutting concerns still leak`],
    code:`// controller (HTTP) -> service (domain) -> repo (data)\n@Controller() class OrdersController {\n  constructor(private svc: OrderService){}\n}`,
    q:`SoC vs SRP?`, a:`SoC is the architectural-scale version; SRP is the same idea at the class level. One principle, two scales.`,
    rel:['srp','mvc','dip'], pdf:null },

  // ---------- GRASP (responsibility assignment — Larman) ----------
  { id:'information-expert', fam:'principle', name:'Information Expert', tag:`Give work to who has the data`,
    intent:`Assign a responsibility to the class that has the information needed to fulfil it.`,
    structure:[[`Expert`,`the class holding the data`],[`Responsibility`,`the task being placed`],[`Information`,`what's needed to do it`]],
    use:[`Deciding which class gets a method`,`Behaviour that needs a class's own data`],
    avoid:[`When it bloats the data-holder or drags in I/O — use Pure Fabrication`],
    pros:[`Behaviour sits with its data`,`Encapsulation, low coupling`], cons:[`Can overload one class`,`May clash with separation of concerns`],
    code:`class Order {\n  items: Item[] = []\n  total(){ return this.items.reduce((s,i)=>s+i.subtotal(), 0) }  // Order owns items\n}`,
    q:`Information Expert vs SRP?`, a:`Expert decides where a responsibility goes (the data-holder); SRP limits how many reasons a class has to change. They can pull opposite ways — balance with Pure Fabrication.`,
    rel:['high-cohesion','low-coupling','srp'], pdf:null },

  { id:'creator', fam:'principle', name:'Creator', tag:`Who instantiates whom`,
    intent:`Let class B create A when B aggregates, contains, records, or closely uses A.`,
    structure:[[`Creator`,`the class that makes the object`],[`Created`,`the new object`],[`Criteria`,`contains / aggregates / uses`]],
    use:[`Deciding which class calls new`,`B already holds or closely uses A`],
    avoid:[`Complex construction — delegate to Factory Method / Builder`],
    pros:[`Low coupling — no extra creator class`,`Natural ownership`], cons:[`Poor fit when creation logic is complex`],
    code:`class Cart {\n  lines: Line[] = []\n  add(p: Product){ this.lines.push(new Line(p)) }  // Cart contains Lines -> Cart creates them\n}`,
    q:`Creator (GRASP) vs Factory Method (GoF)?`, a:`Creator is a principle for deciding who instantiates; Factory Method is a pattern that implements creation via subclassing. Creator often points to where a factory belongs.`,
    rel:['factory-method','information-expert','low-coupling'], pdf:null },

  { id:'controller', fam:'principle', name:'Controller', tag:`First object behind the UI`,
    intent:`Hand a system event to a non-UI object representing the system, a use case, or a root — not the UI widget.`,
    structure:[[`Controller`,`handles a system operation`],[`UI`,`delegates to the controller`],[`Domain`,`coordinated by the controller`]],
    use:[`Routing input from the UI into the domain`,`Use-case / session coordination`],
    avoid:[`A bloated controller doing domain work itself — delegate it`],
    pros:[`Keeps the UI thin`,`Domain logic reused across UIs`], cons:[`Risk of a god controller`,`Over-centralization`],
    code:`@Controller('orders')\nclass OrdersController {        // not the UI — delegates inward\n  place(dto){ return this.orders.place(dto) }\n}`,
    q:`GRASP Controller vs MVC Controller?`, a:`Same idea, different scope: GRASP names the principle (a non-UI object handles system events); MVC's Controller is one concrete realization of it.`,
    rel:['mvc','pure-fabrication','low-coupling'], pdf:null },

  { id:'low-coupling', fam:'principle', name:'Low Coupling', tag:`Minimize dependencies`,
    intent:`Assign responsibilities so dependencies between classes stay few and weak.`,
    structure:[[`Coupling`,`how strongly a class leans on others`],[`Goal`,`limit the ripple of change`],[`Means`,`interfaces, indirection`]],
    use:[`Evaluating a design option`,`Choosing where a method should live`],
    avoid:[`Chasing zero coupling — some is necessary; don't over-indirect`],
    pros:[`Localized change`,`Reuse and testability`], cons:[`Over-decoupling adds indirection and ceremony`],
    code:`// coupled: new SqlOrderRepo() inside the service\n// low coupling: depend on an interface, inject it\nclass OrderService { constructor(private repo: OrderRepo){} }`,
    q:`Low Coupling vs DIP?`, a:`Low Coupling is the goal (few, weak dependencies); DIP is one technique to reach it (depend on abstractions). DIP is the how, Low Coupling the why.`,
    rel:['dip','lod','high-cohesion'], pdf:null },

  { id:'high-cohesion', fam:'principle', name:'High Cohesion', tag:`Keep related work together`,
    intent:`Assign responsibilities so each class keeps a focused, strongly related set.`,
    structure:[[`Cohesion`,`how related a class's duties are`],[`Goal`,`focused, understandable classes`],[`Means`,`split unrelated work out`]],
    use:[`A class doing many unrelated things`,`Balanced against Low Coupling`],
    avoid:[`Splitting so far you get scattered, anemic classes`],
    pros:[`Readable, testable, maintainable`,`Easier reuse`], cons:[`Over-splitting raises coupling and coordination`],
    code:`// low cohesion: Order computes tax, renders PDF, sends email\n// high cohesion: Order · TaxCalc · PayslipPdf · Mailer`,
    q:`High Cohesion vs SRP?`, a:`Nearly the same lens: SRP says "one reason to change"; High Cohesion says "how related are the duties". SRP is the SOLID phrasing of cohesion.`,
    rel:['srp','low-coupling','soc'], pdf:null },

  { id:'polymorphism', fam:'principle', name:'Polymorphism', tag:`Vary by type, not by if/else`,
    intent:`When behaviour varies by type, assign it through polymorphic operations rather than conditionals on type.`,
    structure:[[`Interface`,`the common operation`],[`Variants`,`type-specific implementations`],[`Client`,`calls without type checks`]],
    use:[`switch / if ladders on a type field`,`Pluggable variation by subtype`],
    avoid:[`A single, stable behaviour — polymorphism is needless`],
    pros:[`Open to new types (OCP)`,`Removes conditionals`], cons:[`More classes`,`Indirection if overused`],
    code:`interface Shape { area(): number }\n// instead of switch(shape.kind) — each type implements area()`,
    q:`Polymorphism (GRASP) vs Strategy (GoF)?`, a:`GRASP Polymorphism is the principle (replace type checks with subtype dispatch); Strategy and State are patterns that apply it to swap algorithms or states.`,
    rel:['ocp','lsp','strategy'], pdf:null },

  { id:'pure-fabrication', fam:'principle', name:'Pure Fabrication', tag:`Invent a class to keep design clean`,
    intent:`Assign a cohesive responsibility to an artificial class (not a domain concept) to protect High Cohesion and Low Coupling.`,
    structure:[[`Fabrication`,`a made-up, non-domain class`],[`Reason`,`keep the domain cohesive & decoupled`],[`Examples`,`Service · Repository · Mapper`]],
    use:[`Persistence / mapping / coordination off a domain entity`,`Expert would bloat the data-holder`],
    avoid:[`Inventing classes with no clear responsibility`],
    pros:[`Keeps the domain clean`,`Reusable, cohesive helpers`], cons:[`Too many fabrications fragment the design`],
    code:`// don't put SQL on the Order entity:\nclass OrderRepository { save(o: Order){ /* persistence */ } }  // pure fabrication`,
    q:`When does Pure Fabrication beat Information Expert?`, a:`When Expert would force unrelated duties (e.g. DB I/O) onto a domain class and wreck cohesion — fabricate a Service / Repository instead.`,
    rel:['information-expert','repository','high-cohesion'], pdf:null },

  { id:'indirection', fam:'principle', name:'Indirection', tag:`Add a middleman to decouple`,
    intent:`Assign responsibility to an intermediate object so two components stay decoupled from each other.`,
    structure:[[`Intermediary`,`the mediating object`],[`Parties`,`components kept apart`],[`Effect`,`lower direct coupling`]],
    use:[`Two components shouldn't know each other`,`Insert a seam — adapter, mediator, controller`],
    avoid:[`Layers of indirection "just in case" — hurts clarity`],
    pros:[`Low coupling`,`Swappable, interceptable`], cons:[`More moving parts`,`Harder to trace`],
    code:`// A and B never talk directly:\nclass Mediator { notify(sender, event){ /* route it */ } }`,
    q:`Indirection vs Protected Variations?`, a:`Indirection adds a middleman to decouple; Protected Variations wraps a variation point behind a stable interface. Indirection is a common way to achieve PV.`,
    rel:['mediator','facade','dip'], pdf:null },

  { id:'protected-variations', fam:'principle', name:'Protected Variations', tag:`Wrap what varies behind a stable interface`,
    intent:`Identify points of predicted variation or instability and wrap them behind a stable interface.`,
    structure:[[`Variation point`,`what is likely to change`],[`Stable interface`,`the contract clients depend on`],[`Implementations`,`swapped behind it`]],
    use:[`A known / likely change — vendor, format, platform`,`Shielding clients from churn`],
    avoid:[`Protecting against speculative change — YAGNI; protect predicted variation`],
    pros:[`Change is contained at the seam`,`Pluggable, future-proof`], cons:[`Over-protection adds cost`,`Guessing the wrong seam`],
    code:`interface PaymentGateway { pay(cents: number): Promise<void> }\n// Stripe / PayPal vary behind it; clients never change`,
    q:`Protected Variations vs OCP?`, a:`The same idea from two sources: OCP (SOLID) and Protected Variations (GRASP) both isolate variation behind a stable abstraction. PV is the more general root principle.`,
    rel:['ocp','dip','indirection'], pdf:null },

  // ---------- CREATIONAL ----------
  { id:'singleton', fam:'creational', name:'Singleton', tag:`One instance, one front door`,
    intent:`Guarantee a class has exactly one instance per process and a single global access point.`,
    structure:[[`private ctor`,`blocks external new`],[`static instance`,`the one cached object`],[`getInstance()`,`lazily builds, then reuses`]],
    use:[`One genuinely shared resource (config, connection pool)`,`A single well-known access point is required`],
    avoid:[`Most cases — prefer a DI singleton-scoped service`],
    pros:[`Controlled single access point`], cons:[`Hidden global state`,`Hard to mock`,`Init-order and test coupling`],
    code:`class Config {\n  static #i?: Config\n  static get(){ return Config.#i ??= new Config() }\n}`,
    q:`Why is Singleton often an anti-pattern?`, a:`It's hidden global state — tight coupling, hard to test, unclear lifecycle. Most cases are better served by a DI singleton-scoped service.`,
    rel:['factory-method','dependency-injection','facade'], pdf:GOF+'gof_05_singleton_en_v5.pdf' },

  { id:'factory-method', fam:'creational', name:'Factory Method', tag:`Let subclasses choose the type`,
    intent:`Define an interface for creating an object, but let subclasses decide which class to instantiate.`,
    structure:[[`Creator`,`declares the factory method`],[`ConcreteCreator`,`overrides it to pick the class`],[`Product`,`common interface`],[`ConcreteProduct`,`the object actually created`]],
    use:[`A class can't anticipate the exact type it must create`,`Localize object creation behind one overridable method`],
    avoid:[`Only one product type will ever exist — just use new`],
    pros:[`Decouples client from concrete classes`,`OCP for new products`], cons:[`A subclass per product`,`More indirection`],
    code:`abstract class Dialog {\n  abstract createButton(): Button\n  render(){ this.createButton().paint() }\n}\nclass WinDialog extends Dialog { createButton(){ return new WinButton() } }`,
    q:`Factory Method vs Abstract Factory?`, a:`Factory Method makes one product via subclassing; Abstract Factory makes families of related products via composition.`,
    rel:['abstract-factory','prototype','ocp'], pdf:GOF+'gof_03_factory_en_v1.pdf' },

  { id:'abstract-factory', fam:'creational', name:'Abstract Factory', tag:`Families of related objects`,
    intent:`Provide an interface to create families of related objects without specifying concrete classes.`,
    structure:[[`AbstractFactory`,`one create-method per product`],[`ConcreteFactory`,`one consistent family`],[`Products`,`a related set`]],
    use:[`UI toolkits and themes`,`Cross-platform widget sets — swap a whole family at once`],
    avoid:[`Products aren't actually related or co-varying`],
    pros:[`Guarantees compatible products`,`Isolates concrete classes`], cons:[`Adding a new product kind touches every factory`],
    code:`interface UIFactory { button(): Button; checkbox(): Checkbox }\nclass MacFactory implements UIFactory {\n  button(){ return new MacButton() }\n  checkbox(){ return new MacCheckbox() }\n}`,
    q:`When does Abstract Factory hurt?`, a:`Adding a new product type changes the interface and every concrete factory — open for families, closed against new product kinds.`,
    rel:['factory-method','builder','singleton'], pdf:GOF+'gof_01_abstract-factory_en_v1.pdf' },

  { id:'builder', fam:'creational', name:'Builder', tag:`Construct step by step`,
    intent:`Separate the construction of a complex object from its representation so one process can build different results.`,
    structure:[[`Builder`,`step methods`],[`Director`,`(optional) orders the steps`],[`Product`,`the assembled result`]],
    use:[`Many optional params / telescoping constructors`,`Immutable objects with validation`],
    avoid:[`Simple objects with few fields — overkill`],
    pros:[`Readable construction`,`Validates before build()`], cons:[`More boilerplate`,`A two-phase object`],
    code:`const q = new QueryBuilder()\n  .select('id').from('users')\n  .where('age > 18').limit(10).build()`,
    q:`Builder vs Abstract Factory?`, a:`Builder constructs one complex object step-by-step (cares how); Abstract Factory returns families immediately (cares what).`,
    rel:['abstract-factory','factory-method','prototype'], pdf:GOF+'gof_02_builder_en_v1.pdf' },

  { id:'prototype', fam:'creational', name:'Prototype', tag:`Create by cloning`,
    intent:`Create new objects by copying an existing instance (the prototype) instead of constructing from scratch.`,
    structure:[[`Prototype`,`declares clone()`],[`ConcretePrototype`,`implements the copy`],[`Client`,`clones instead of new`]],
    use:[`Object creation is expensive`,`Many near-identical configured instances`],
    avoid:[`Objects are cheap to build`,`Deep graphs with cycles are painful to copy`],
    pros:[`Skips costly initialization`,`Runtime-configurable instances`], cons:[`Deep vs shallow copy hazards`,`Cloning complex graphs`],
    code:`class Doc {\n  constructor(public body = '', public tags = ['draft']) {}\n  clone(){ return new Doc(this.body, [...this.tags]) }  // copies itself\n}\nconst copy = new Doc().clone()   // independent of the original`,
    q:`Shallow vs deep clone trap?`, a:`A shallow clone shares nested references — mutating the copy mutates the original. Use deep copy (structuredClone) for nested state.`,
    rel:['factory-method','abstract-factory','flyweight'], pdf:GOF+'gof_04_prototype_en_v1.pdf' },

  // ---------- STRUCTURAL ----------
  { id:'adapter', fam:'structural', name:'Adapter', tag:`Make incompatible interfaces fit`,
    intent:`Convert a class's interface into another interface that clients expect.`,
    structure:[[`Target`,`interface the client wants`],[`Adaptee`,`existing incompatible class`],[`Adapter`,`translates between them`]],
    use:[`Integrate a third-party or legacy API`,`Two interfaces almost match`],
    avoid:[`You control both sides — fix the interface instead`],
    pros:[`Reuse without modifying either side`], cons:[`An extra layer`,`Can mask a deeper model mismatch`],
    code:`class StripeAdapter implements PaymentGateway {\n  constructor(private s: Stripe) {}\n  pay(cents:number){ return this.s.charge(cents) }\n}`,
    q:`Adapter vs Facade?`, a:`Adapter changes one interface to a specific expected one; Facade invents a new, simpler interface over a whole subsystem.`,
    rel:['facade','decorator','proxy'], pdf:GOF+'gof_06_adapter_en_v1.pdf' },

  { id:'bridge', fam:'structural', name:'Bridge', tag:`Split abstraction from implementation`,
    intent:`Decouple an abstraction from its implementation so the two can vary independently.`,
    structure:[[`Abstraction`,`high-level control, holds an Implementor`],[`Implementor`,`platform / detail interface`],[`Refined / Concrete`,`vary on each side`]],
    use:[`Two independent dimensions (shape x renderer)`,`Avoid a class explosion of m x n`],
    avoid:[`Only one dimension varies — YAGNI`],
    pros:[`m + n classes instead of m x n`,`Swap implementation at runtime`], cons:[`Upfront indirection`,`Harder to grasp`],
    code:`class Shape { constructor(protected r: Renderer){} }\nclass Circle extends Shape { draw(){ this.r.drawCircle() } }\n// Renderer: SvgRenderer | CanvasRenderer`,
    q:`Bridge vs Strategy — both compose an interface?`, a:`Structurally similar. Bridge is structural (separate two hierarchies that vary); Strategy is behavioral (swap an algorithm). Intent differs.`,
    rel:['strategy','adapter','abstract-factory'], pdf:GOF+'gof_07_bridge_en_v1.pdf' },

  { id:'composite', fam:'structural', name:'Composite', tag:`Treat tree and leaf alike`,
    intent:`Compose objects into tree structures and let clients treat individual objects and compositions uniformly.`,
    structure:[[`Component`,`common interface`],[`Leaf`,`no children`],[`Composite`,`holds children, delegates`]],
    use:[`Part-whole hierarchies (files/folders, UI trees, menus)`],
    avoid:[`Flat, non-hierarchical data`],
    pros:[`Uniform client code`,`Recursion is natural`], cons:[`Type safety is loosened`,`Can over-generalize leaves`],
    code:`interface Node { size(): number }\nclass File implements Node { size(){ return this.bytes } }\nclass Dir implements Node { size(){ return sum(this.kids.map(k=>k.size())) } }`,
    q:`Composite's main trade-off?`, a:`Uniformity vs type safety — a shared interface can expose child-only ops (add/remove) on leaves. You choose transparency vs safety.`,
    rel:['decorator','iterator','visitor'], pdf:GOF+'gof_08_composite_en_v1.pdf' },

  { id:'decorator', fam:'structural', name:'Decorator', tag:`Add behavior by wrapping`,
    intent:`Attach responsibilities to an object dynamically by wrapping it in objects of the same interface.`,
    structure:[[`Component`,`shared interface`],[`ConcreteComponent`,`the base object`],[`Decorator`,`wraps and adds behavior`]],
    use:[`Optional features combined at runtime`,`Avoid a subclass explosion from feature combos`],
    avoid:[`Deep wrapper stacks become hard to trace; order-sensitive`],
    pros:[`Composition over inheritance`,`Mix features freely`], cons:[`Many small objects`,`Wrapping order matters`],
    code:`const svc = new RetryDecorator(\n  new CacheDecorator(new HttpService())\n)`,
    q:`Decorator vs Proxy vs Adapter?`, a:`Same wrapping shape, different intent: Decorator adds behavior, Proxy controls access, Adapter changes the interface.`,
    rel:['proxy','adapter','composite'], pdf:GOF+'gof_09_decorator_en_v1.pdf' },

  { id:'facade', fam:'structural', name:'Facade', tag:`One simple door to a subsystem`,
    intent:`Provide a unified, simplified interface to a set of interfaces in a subsystem.`,
    structure:[[`Facade`,`simple entry point`],[`Subsystem`,`many complex classes behind it`]],
    use:[`Tame a complex library`,`Provide a coarse API for common tasks`],
    avoid:[`Hiding so much it becomes a god object`],
    pros:[`Reduces coupling to the subsystem`,`Easier onboarding`], cons:[`Can become a bottleneck / god class`,`Hides power-user features`],
    code:`class MediaFacade {\n  convert(file){ /* uses Codec, Muxer, IO ... */ }\n}\n// client calls one method, not five classes`,
    q:`Facade vs Adapter?`, a:`Facade simplifies a whole subsystem behind a new API; Adapter makes one existing interface match a specific expected one.`,
    rel:['adapter','mediator','proxy'], pdf:GOF+'gof_10_facade_en_v1.pdf' },

  { id:'flyweight', fam:'structural', name:'Flyweight', tag:`Share to save memory`,
    intent:`Use sharing to support huge numbers of fine-grained objects by separating intrinsic (shared) from extrinsic (context) state.`,
    structure:[[`Flyweight`,`intrinsic, shared state`],[`FlyweightFactory`,`caches and returns shared instances`],[`Context`,`supplies extrinsic state`]],
    use:[`Millions of similar objects (glyphs, tiles, particles)`],
    avoid:[`Few objects, or state that can't be split cleanly`],
    pros:[`Big memory savings`,`Cache reuse`], cons:[`Added complexity`,`Extrinsic state must be passed in everywhere`],
    code:`const cache = new Map() // char -> shared Glyph\nconst glyph = c => cache.get(c)\n  ?? (cache.set(c, new Glyph(c)), cache.get(c))`,
    q:`Intrinsic vs extrinsic state?`, a:`Intrinsic is shared and immutable (lives in the flyweight); extrinsic is context-specific (position, color) and passed by the client at use time.`,
    rel:['prototype','proxy','composite'], pdf:GOF+'gof_11_flyweight_en_v1.pdf' },

  { id:'proxy', fam:'structural', name:'Proxy', tag:`A stand-in that controls access`,
    intent:`Provide a surrogate for another object to control access to it.`,
    structure:[[`Subject`,`shared interface`],[`RealSubject`,`the actual object`],[`Proxy`,`mediates access — lazy, remote, protection`]],
    use:[`Lazy loading`,`Access control, caching, remote stubs`],
    avoid:[`No access concern — a plain reference is simpler`],
    pros:[`Adds control transparently`,`Lazy and cheap`], cons:[`Indirection / latency`,`Another layer to reason about`],
    code:`class ImageProxy implements Image {\n  private real?: RealImage\n  render(){ (this.real ??= new RealImage(this.path)).render() }\n}`,
    q:`Proxy vs Decorator?`, a:`Identical structure. Proxy controls or limits access (often same lifecycle); Decorator augments behavior. Intent separates them.`,
    rel:['decorator','adapter','facade'], pdf:GOF+'gof_12_proxy_en_v1.pdf' },

  // ---------- BEHAVIORAL ----------
  { id:'chain', fam:'behavioral', name:'Chain of Responsibility', tag:`Pass the request down a chain`,
    intent:`Pass a request along a chain of handlers; each decides to handle it or forward it.`,
    structure:[[`Handler`,`interface + next link`],[`ConcreteHandler`,`handles or passes on`],[`Client`,`sends to the chain head`]],
    use:[`Middleware pipelines`,`Escalation / approval flows; event filtering`],
    avoid:[`Exactly one known handler — just call it`],
    pros:[`Decouples sender from receiver`,`Add or reorder handlers freely`], cons:[`No guarantee the request is handled`,`Long chains are hard to debug`],
    code:`app.use(auth)\napp.use(rateLimit)\napp.use(handler)\n// each middleware: handle(req) or call next()`,
    q:`Where do you use Chain daily?`, a:`HTTP middleware (Express, Nest guards/interceptors), logging pipelines, event handlers — all chain-of-responsibility.`,
    rel:['command','decorator','mediator'], pdf:GOF+'gof_13_chain_en_v1.pdf' },

  { id:'command', fam:'behavioral', name:'Command', tag:`Turn a request into an object`,
    intent:`Encapsulate a request as an object, letting you parameterize, queue, log, and undo operations.`,
    structure:[[`Command`,`execute() / undo()`],[`Invoker`,`triggers commands`],[`Receiver`,`does the real work`]],
    use:[`Undo/redo`,`Task queues and jobs; macro recording`],
    avoid:[`Trivial direct calls — a needless object`],
    pros:[`Decouples invoker from work`,`Enables undo, queue, log`], cons:[`Many small command classes`,`Indirection`],
    code:`interface Command { execute(): void; undo(): void }\nclass AddText implements Command { execute(){} undo(){} }\nhistory.push(cmd); cmd.execute()`,
    q:`How does Command enable undo?`, a:`Each command stores enough state to reverse itself (undo()); a history stack replays or reverts commands in order.`,
    rel:['chain','memento','strategy'], pdf:GOF+'gof_14_command_en_v1.pdf' },

  { id:'interpreter', fam:'behavioral', name:'Interpreter', tag:`Evaluate a little language`,
    intent:`Given a language, define a representation for its grammar plus an interpreter to evaluate sentences.`,
    structure:[[`AbstractExpression`,`interpret(ctx)`],[`Terminal / NonTerminal`,`grammar nodes`],[`Context`,`input and state`]],
    use:[`Small DSLs`,`Rule engines; query/filter expressions`],
    avoid:[`Complex grammars — use a real parser / AST tool`],
    pros:[`Grammar maps directly to classes`,`Easy to extend rules`], cons:[`A class per rule explodes`,`Poor performance for big grammars`],
    code:`// (age > 18) AND (country = 'UA')\nnew And(new Gt('age',18), new Eq('country','UA'))\n  .interpret(ctx)`,
    q:`When should you NOT use Interpreter?`, a:`Anything beyond a tiny grammar — it doesn't scale. Reach for a parser generator or expression library instead.`,
    rel:['composite','visitor','strategy'], pdf:GOF+'gof_15_interpreter_en_v1.pdf' },

  { id:'iterator', fam:'behavioral', name:'Iterator', tag:`Traverse without exposing internals`,
    intent:`Provide a way to access elements of a collection sequentially without exposing its underlying representation.`,
    structure:[[`Iterator`,`next() / hasNext()`],[`Aggregate`,`creates an iterator`],[`Client`,`loops via the iterator`]],
    use:[`Custom collections`,`Uniform traversal; lazy or infinite sequences`],
    avoid:[`Plain arrays with built-in iteration`],
    pros:[`Hides the structure`,`Multiple simultaneous traversals`], cons:[`Overhead for simple cases`],
    code:`function* range(a,b){ for(let i=a;i<b;i++) yield i }\nfor (const n of range(0,5)) use(n)`,
    q:`How is Iterator built into JS?`, a:`The iteration protocol — Symbol.iterator plus generators (function*) — is Iterator; for...of consumes any iterable.`,
    rel:['composite','visitor','strategy'], pdf:GOF+'gof_16_iterator_en_v1.pdf' },

  { id:'mediator', fam:'behavioral', name:'Mediator', tag:`Centralize many-to-many talk`,
    intent:`Define an object that encapsulates how a set of objects interact, so they don't refer to each other directly.`,
    structure:[[`Mediator`,`coordinates colleagues`],[`Colleague`,`talks only to the mediator`]],
    use:[`Complex UI forms`,`Chat rooms; air-traffic-style coordination`],
    avoid:[`Few, simple interactions`],
    pros:[`Reduces n x n coupling to n`,`Centralizes control`], cons:[`The mediator can become a god object`],
    code:`class FormMediator {\n  changed(field){ /* enable/disable others */ }\n}\n// each widget notifies the mediator, not its siblings`,
    q:`Mediator vs Observer?`, a:`Observer is one-to-many broadcast; Mediator centralizes many-to-many coordination logic in a single hub.`,
    rel:['observer','facade','command'], pdf:GOF+'gof_17_mediator_en_v1.pdf' },

  { id:'memento', fam:'behavioral', name:'Memento', tag:`Capture and restore state`,
    intent:`Capture an object's internal state without violating encapsulation, so it can be restored later.`,
    structure:[[`Originator`,`creates and restores mementos`],[`Memento`,`opaque state snapshot`],[`Caretaker`,`holds mementos (history)`]],
    use:[`Undo/redo`,`Snapshots, checkpoints, transaction rollback`],
    avoid:[`Large, expensive state snapshotted frequently`],
    pros:[`Encapsulation preserved`,`Clean undo`], cons:[`Memory cost of snapshots`,`Snapshot-frequency tuning`],
    code:`const snap = editor.save()        // -> Memento\neditor.type('...')\neditor.restore(snap)              // undo`,
    q:`Memento vs Command for undo?`, a:`Command reverses via inverse operations; Memento restores a whole saved snapshot. They combine — commands can store mementos.`,
    rel:['command','state','prototype'], pdf:GOF+'gof_18_memento_en_v1.pdf' },

  { id:'observer', fam:'behavioral', name:'Observer', tag:`Notify dependents on change`,
    intent:`Define a one-to-many dependency so that when one object changes state, all its dependents are notified.`,
    structure:[[`Subject`,`registers and notifies observers`],[`Observer`,`update() reacts`],[`Subscription`,`attach / detach`]],
    use:[`Event systems`,`Reactive UI / state; model-view sync`],
    avoid:[`Complex update cascades — prefer an event bus / reactive streams`],
    pros:[`Loose coupling`,`Dynamic subscribers`], cons:[`Update storms`,`Memory leaks if not detached`,`Order undefined`],
    code:`subject.subscribe(o => render(o))\nsubject.notify(state)   // all observers run`,
    q:`Observer vs Pub/Sub?`, a:`Observer: the subject holds references to observers directly. Pub/Sub inserts a broker/channel, fully decoupling the two ends.`,
    rel:['mediator','command','mvvm'], pdf:GOF+'gof_19_observer_en_v1.pdf' },

  { id:'state', fam:'behavioral', name:'State', tag:`Behavior changes with state`,
    intent:`Allow an object to alter its behavior when its internal state changes — it appears to change class.`,
    structure:[[`Context`,`holds the current state`],[`State`,`interface for state-specific behavior`],[`ConcreteState`,`transitions to the next`]],
    use:[`State machines (order/payment lifecycle)`,`Mode-dependent behavior`],
    avoid:[`Few states with trivial branching — an enum/switch is fine`],
    pros:[`Removes big conditionals`,`Transitions are explicit`], cons:[`A class per state`,`Transition logic can scatter`],
    code:`class Order {\n  state: OrderState = new Pending()\n  pay(){ this.state = this.state.pay(this) }\n}`,
    q:`State vs Strategy?`, a:`Same structure. State objects transition themselves based on context; Strategy is chosen externally by the client and usually doesn't self-switch.`,
    rel:['strategy','command','memento'], pdf:GOF+'gof_20_state_en_v1.pdf' },

  { id:'strategy', fam:'behavioral', name:'Strategy', tag:`Swap the algorithm at runtime`,
    intent:`Define a family of algorithms, encapsulate each one, and make them interchangeable.`,
    structure:[[`Strategy`,`common algorithm interface`],[`ConcreteStrategy`,`one algorithm`],[`Context`,`delegates to a strategy`]],
    use:[`Pluggable behavior (sort, pricing, auth, compression)`,`Replace an if/else ladder`],
    avoid:[`Behavior never varies — needless indirection`],
    pros:[`OCP`,`Test algorithms in isolation`,`Swap at runtime`], cons:[`Client must know the strategies`,`More objects`],
    code:`class Sorter {\n  constructor(private cmp: Comparator){}\n  run(a){ return a.sort(this.cmp) }\n}\nnew Sorter(byPrice).run(items)`,
    q:`Strategy vs State vs Bridge?`, a:`Same shape. Strategy: client picks an algorithm. State: object self-transitions. Bridge: structural split of two hierarchies.`,
    rel:['state','bridge','ocp','polymorphism'], pdf:GOF+'gof_21_strategy_en_v1.pdf' },

  { id:'template-method', fam:'behavioral', name:'Template Method', tag:`Fixed skeleton, pluggable steps`,
    intent:`Define the skeleton of an algorithm in a base method, deferring some steps to subclasses.`,
    structure:[[`AbstractClass`,`template method + abstract steps`],[`ConcreteClass`,`overrides the steps`]],
    use:[`Frameworks with a fixed flow + custom hooks`,`Shared algorithm, varying parts`],
    avoid:[`Steps vary so much the skeleton is meaningless — prefer Strategy`],
    pros:[`Reuse the invariant flow`,`Control the extension points`], cons:[`Inheritance-bound`,`Fragile base class`],
    code:`abstract class Importer {\n  run(){ this.parse(); this.validate(); this.save() }\n  abstract parse(): void\n}`,
    q:`Template Method vs Strategy?`, a:`Template Method uses inheritance (override steps); Strategy uses composition (inject behavior). Prefer Strategy when you need a runtime swap.`,
    rel:['strategy','factory-method','coi'], pdf:GOF+'gof_22_template_en_v1.pdf' },

  { id:'visitor', fam:'behavioral', name:'Visitor', tag:`Add operations without touching classes`,
    intent:`Represent an operation on elements of an object structure, letting you add new operations without changing the elements.`,
    structure:[[`Visitor`,`visitX() per element type`],[`Element`,`accept(visitor)`],[`ObjectStructure`,`iterates elements`]],
    use:[`Operations over a stable AST/tree (type-check, pretty-print, eval)`],
    avoid:[`Element types change often — Visitor makes that painful`],
    pros:[`Add operations easily`,`Group related logic together`], cons:[`A new element type touches every visitor`,`Double-dispatch overhead`],
    code:`class AreaVisitor {\n  visitCircle(c){} visitSquare(s){}\n}\nshape.accept(new AreaVisitor())`,
    q:`Visitor's core trade-off (the expression problem)?`, a:`Easy to add operations, hard to add element types — the inverse of OOP polymorphism. Choose by which axis changes more.`,
    rel:['composite','interpreter','iterator'], pdf:GOF+'gof_23_visitor_en_v1.pdf' },

  // ---------- ARCHITECTURAL ----------
  { id:'mvc', fam:'architectural', name:'MVC', full:`Model–View–Controller`, tag:`Model, View, Controller`,
    intent:`Separate data (Model), presentation (View) and input handling (Controller) so they evolve independently.`,
    structure:[[`Model`,`data + business rules`],[`View`,`renders state`],[`Controller`,`handles input, updates the model`]],
    use:[`Server-rendered web apps`,`Classic UI frameworks`],
    avoid:[`Tiny apps`,`Fat controllers used as a dumping ground`],
    pros:[`Separation of concerns`,`Parallel work across layers`], cons:[`Controller bloat`,`View–Model coupling creep`],
    code:`@Controller('orders') class OrdersController {\n  @Get() list(){ return this.orders.all() }  // -> View renders\n}`,
    q:`MVC vs MVP vs MVVM?`, a:`Different view-binding: MVC's controller mediates; MVP's presenter updates a passive view; MVVM binds the view to a view-model (two-way).`,
    rel:['mvp','mvvm','soc','controller'], pdf:null },

  { id:'mvp', fam:'architectural', name:'MVP', full:`Model–View–Presenter`, tag:`Presenter drives a passive view`,
    intent:`An MVC variant where a Presenter holds all UI logic and updates a passive View through an interface.`,
    structure:[[`View`,`passive, interface-driven`],[`Presenter`,`UI logic, calls the view`],[`Model`,`domain / data`]],
    use:[`Testable UI (classic Android, WinForms)`,`Views that are hard to unit-test`],
    avoid:[`Simple views where binding (MVVM) is enough`],
    pros:[`Highly testable presenter`,`The view is dumb`], cons:[`Presenter can grow large`,`More interfaces / boilerplate`],
    code:`interface LoginView { showError(m:string): void }\nclass LoginPresenter {\n  constructor(private v: LoginView){}\n  submit(){ /* ... */ }\n}`,
    q:`MVP vs MVC?`, a:`In MVP the view is fully passive with a 1:1 presenter reference; in MVC the controller handles input and the view may read the model directly.`,
    rel:['mvc','mvvm','dip'], pdf:null },

  { id:'mvvm', fam:'architectural', name:'MVVM', full:`Model–View–ViewModel`, tag:`Bind view to a view-model`,
    intent:`Separate view from logic via a ViewModel that exposes bindable state and commands; the view binds (often two-way) to it.`,
    structure:[[`View`,`declarative bindings`],[`ViewModel`,`state + commands, no view reference`],[`Model`,`domain / data`]],
    use:[`Data-binding frameworks (Angular, Vue, WPF)`,`Reactive UIs`],
    avoid:[`Static pages where binding overhead isn't justified`],
    pros:[`Testable view-model`,`Less glue code via binding`], cons:[`Binding "magic" and debugging`,`Logic can leak into the view`],
    code:`// Angular: component = ViewModel, template binds to signals\ncount = signal(0)\ninc(){ this.count.update(v => v + 1) }`,
    q:`Why does MVVM fit Angular/Vue?`, a:`Their reactive binding (signals/refs + templates) gives the ViewModel→View sync the pattern needs; explicit two-way (ngModel / v-model) closes the loop back.`,
    rel:['mvc','observer','soc'], pdf:null },

  { id:'repository', fam:'architectural', name:'Repository', tag:`Collection-like access to aggregates`,
    intent:`Mediate between the domain and data layers, exposing a collection-like interface for accessing aggregates.`,
    structure:[[`Repository`,`find / add / remove in domain terms`],[`Aggregate`,`the persisted unit`],[`Mapper / ORM`,`behind the port`]],
    use:[`Keep persistence out of the domain`,`Swap the DB or fake it in tests`],
    avoid:[`Thin CRUD apps where a generic repo becomes a leaky abstraction`],
    pros:[`Clean, testable domain`,`Centralized query logic`], cons:[`Anemic generic repos`,`Leaky, ad-hoc query methods`],
    code:`interface OrderRepo {\n  byId(id: Id): Promise<Order>\n  save(o: Order): Promise<void>\n}\nclass SqlOrderRepo implements OrderRepo { /* TypeORM */ }`,
    q:`Repository vs DAO?`, a:`A DAO is table/row-oriented and close to the DB; a Repository is aggregate/domain-oriented and speaks the ubiquitous language.`,
    rel:['unit-of-work','dip','dependency-injection'], pdf:DDD_TAC },

  { id:'unit-of-work', fam:'architectural', name:'Unit of Work', tag:`One transaction, one commit`,
    intent:`Track objects changed during a business transaction and coordinate writing them out — and concurrency — in one commit.`,
    structure:[[`UnitOfWork`,`tracks new / dirty / removed`],[`commit()`,`one atomic flush`],[`Repositories`,`enlist their changes`]],
    use:[`Multiple writes must be atomic`,`Reduce round-trips and keep consistency`],
    avoid:[`Single-statement writes`,`Where the ORM session already does it`],
    pros:[`Atomicity`,`Fewer DB round-trips`,`Consistency`], cons:[`Complexity`,`Long units risk lock contention`],
    code:`await uow.run(async () => {\n  orders.add(order)\n  inventory.decrement(item)\n})  // single transaction commit`,
    q:`Where have you already used Unit of Work?`, a:`ORM sessions/transactions — TypeORM's transaction/EntityManager, EF's DbContext, Hibernate's session all implement it.`,
    rel:['repository','command','dip'], pdf:DDD_TAC },

  { id:'dependency-injection', fam:'architectural', name:'Dependency Injection', tag:`Inject collaborators from outside`,
    intent:`Supply an object's dependencies from outside — injected at creation, via a setter, or through a container — instead of having it create them itself.`, // CHANGED: drop bare word "constructor" (satori-html drops Object.prototype keys -> word vanished on the PDF); reworded, still accurate for the HTML maps
    structure:[[`Client`,`declares its dependencies as parameters`],[`Injector / Container`,`wires concrete impls`],[`Service`,`the provided dependency`]], // CHANGED: "constructor params" -> "parameters" (same satori-html drop)
    use:[`Realizing DIP`,`Testability via mocks; swapping implementations or config`],
    avoid:[`Tiny scripts`,`Over-configured containers for trivial graphs`],
    pros:[`Testable, decoupled`,`Centralized wiring and lifecycles`], cons:[`Indirection`,`Container "magic"`,`Startup wiring complexity`],
    code:`@Injectable() class OrderService {\n  constructor(private repo: OrderRepo){}\n}\n// Nest module wires OrderRepo -> SqlOrderRepo`,
    q:`Is DI the same as a DI container?`, a:`No. DI is the technique (pass dependencies in); a container is optional tooling that automates wiring. You can do DI by hand.`,
    rel:['dip','repository','singleton'], pdf:null },
];

// Map each node to a sub-group id. GoF nodes already carry their sub-group in
// `fam` (creational/structural/behavioral); only principle + architectural need mapping.
const SUBMAP = {
  srp:'solid', ocp:'solid', lsp:'solid', isp:'solid', dip:'solid',
  dry:'simplicity', kiss:'simplicity', yagni:'simplicity',
  lod:'coupling', coi:'coupling', soc:'coupling',
  'information-expert':'grasp', creator:'grasp', controller:'grasp', 'low-coupling':'grasp',
  'high-cohesion':'grasp', polymorphism:'grasp', 'pure-fabrication':'grasp', indirection:'grasp', 'protected-variations':'grasp',
  mvc:'presentation', mvp:'presentation', mvvm:'presentation',
  repository:'data', 'unit-of-work':'data',
  'dependency-injection':'composition',
};
const SUBOF = {}; SUBS.forEach(s => SUBOF[s.id] = s);
const cap = s => s.charAt(0).toUpperCase() + s.slice(1);

// Where each non-GoF concept's deep-dive PDF lives (relative to the HTML maps).
const SUBFOLDER = {
  solid: 'Principles/Solid', simplicity: 'Principles/Simplicity_and_Clarity',
  coupling: 'Principles/Coupling_and_OO_Design', grasp: 'Principles/GRASP',
  presentation: 'Architectural/Presentation', data: 'Architectural/Data_and_persistence',
  composition: 'Architectural/Composition',
  creational: 'GoF_Design_Patterns/Creational', structural: 'GoF_Design_Patterns/Structural',
  behavioral: 'GoF_Design_Patterns/Behavioral',
};

// Deep-dive links are AUTO-DISCOVERED at build time: if a concept's PDF exists at
// <sub-folder>/<id>_deep-dive_en.pdf the button wires itself — no central list to
// edit, so parallel sessions never collide. GoF posters are always present.
const fs = require('fs'), pathlib = require('path');
NODES.forEach(n => {
  n.sub = SUBMAP[n.id] || n.fam;
  n.group = SUBOF[n.sub].group;
  if (n.group === 'gof') {
    const sub = cap(n.sub), oldFile = String(n.pdf).split('/').pop();
    const newAbs = pathlib.join(__dirname, '..', 'GoF_Design_Patterns', sub, `${n.id}_deep-dive_en.pdf`);
    n.pdf = fs.existsSync(newAbs)
      ? `./GoF_Design_Patterns/${sub}/${n.id}_deep-dive_en.pdf`   // new gold deep-dive (once rendered)
      : `./GoF_Design_Patterns/${sub}/${oldFile}`;                // fallback: existing GoF poster
  } else {
    const folder = SUBFOLDER[n.sub];
    const exists = folder && fs.existsSync(pathlib.join(__dirname, '..', folder, `${n.id}_deep-dive_en.pdf`));
    n.pdf = exists ? `./${folder}/${n.id}_deep-dive_en.pdf` : null;
  }
  if (process.env.DPMAP_NO_DEEPDIVE) n.pdf = null;   // build a PDF-free site: buttons show "coming soon", no 404
});

// Recommended learning order (fast-immersion route), grouped into stages.
const PATH = [
  { stage:`Principles first`, why:`Patterns are concrete applications of these rules — learn what you're optimizing for before the patterns themselves.`,
    ids:['kiss','dry','yagni','srp','ocp','lsp','isp','dip','information-expert','creator','controller','low-coupling','high-cohesion','polymorphism','pure-fabrication','indirection','protected-variations','coi','lod','soc'] },
  { stage:`Creational`, why:`The first patterns tame object creation — separating "what to make" from "who makes it".`,
    ids:['factory-method','abstract-factory','builder','prototype','singleton'] },
  { stage:`Structural`, why:`With creation handled, see how objects wrap, adapt and combine into larger shapes.`,
    ids:['adapter','facade','decorator','proxy','composite','bridge','flyweight'] },
  { stage:`Behavioral`, why:`The largest family: how responsibility is assigned and how objects communicate.`,
    ids:['strategy','state','observer','command','template-method','iterator','chain','mediator','memento','visitor','interpreter'] },
  { stage:`Architectural`, why:`Zoom out from classes to the whole app — layering, presentation and wiring.`,
    ids:['mvc','mvp','mvvm','repository','unit-of-work','dependency-injection'] },
];

if (typeof module !== 'undefined') module.exports = { GROUPS, SUBS, NODES, PATH, SUBFOLDER };
